### PR TITLE
option for serializing blank fields

### PR DESCRIPTION
**Pull request by khaled**

### CODE REVIEW

**Comment by veacks** [comment]
Any chance to see a merge of this feature ?
It's very usefull for Backbone Users...

**Comment by khaled** [comment]
@defunctzombie I've changed the option name per your request...

**Comment by defunctzombie** [comment]
@khaled looks good, can you please squash the commits and I will merge.

**Comment by khaled** [comment]
All set.

**Comment by veacks** [comment]
@khaled, @defunctzombie
I have done another pull-request more advanced and I have updated the unit tests for this feature.

After testing it myself, the version of @khaled version to apply to my application, it seems to have some unespected behaviours with empty radio buttons, empty multi-level select and some few others that I don't remember etc...

@defunctzombie Can you please have a look on the pull request I have made  ?

@khaled hope you don't mind.

**Comment by defunctzombie** [comment]
@veacks took a look. Your PR is doing more than this one. Could you elaborate a bit about the need for those additional checks?

@khaled does that PR suit your needs or do the added checks alter the behavior more than you were expecting?

**Comment by defunctzombie** [comment]
Thanks for being vigilant about this folks. I do want to merge this feature in but also want to make sure we capture the intent properly to avoid breaking existing users and having to fix this up after release.

**Comment by veacks** [comment]
First sorry for my spelling, english isnt my native language. Hope it will be understandable.

In short, more and less the same as @khaled does initially but: 
- it wasn't setted up for the multiple-select tags
- wasn't setted up and buggy for input type radio (it was treating radio buttons and checkbox as if it was the same kind of input but in fact these two have 2 diferent behaviours).
- Also this one do not change at all the behavior of the initial script if option.empty is at false or null, so it guarantee the compatibility with the old versions.

The long answer:
# For the radion buttons
Radio have the same behaviour as a select tag and Checkbox have a same as a multiselect.
It's not a problem for Checkbox because each one are true or false for a same group

But for radio, you need to take care of the orther elements with the same name and cannot be processed in the same loop

the @khaled version does:
on line 59  (@khaled) `(!val && !options.empty)`

That's why the tests fails when you run on radio button, when @khaled tried to don't run continue, it's not acting that radio buttons are a group of input.

on line 41 (mine) `var radio_store = {}`

What I do is storring each `name` of radio (group of radio) in an object ouside the loop as false by default.
If one of these have a value, I set the flag for the group at true.

on line 64 (mine)
```
// If we want the empty elements for radio
if (options.empty && element.type === 'radio') {
    if (!radio_store[element.name] && !element.checked) {
        radio_store[element.name] = false
    }
    else if (element.checked) {
        radio_store[element.name] = true
    }
}
```

Then, when the loop is finish and if the option.empty is at true, I do the serialisation to all groups marked at false (the empty ones).
on line 110 (mine)
```
// Check for all empty radio buttons and serialize them with key=""
if (options.empty) {
    for (var key in radio_store) {
        if (!radio_store[key]) {
            result = serializer(result, key, "");
        }
    }
}
```
So like that we can have the empty radio buttons.

# For the checkboxes
I keep the same behaviour of @khaled for these one but he is sending `element.checked` as value which mean true or false.

What a checkbox does is, sending a value of the field if checked
So if we want to get the unchecked state, we need to send an empty value (after it's the interpretation of the developper to translate it at true or false for the needs)

# For multiple select

Just did a flag as not selected by default.
Set the flag to true if one or more options are selected
If there is no options selected and the option.empty is set tu true
send a blank value.

on line 90 (mine)
```
var selectOptions = element.options;
var isSelectedOptions = false;
for (var j=0 ; j<selectOptions.length ; ++j) {
    var option = selectOptions[j];
    if (option.selected) {
        isSelectedOptions = true
        result = serializer(result, key, option.value);
     }
 }
 
// Serialize if no selected options and options.empty is true
if (!isSelectedOptions && options.empty) {
    result = serializer(result, key, "");
}
```

### On the tests/index.js

Just tested in all cases if we have the behaviour expected when empty is setup and if empty+hash is setup

**Comment by defunctzombie** [comment]
@veacks thank you very much for the detailed explanation. @khaled unless there is an objection, can you please test @veacks PR for your use case and I will merge that one instead.

**Comment by veacks** [comment]
@defunctzombie, @khaled 
Hi guys, any news about the merge?

**Comment by defunctzombie** [comment]
I was waiting for a review. Guess he is busy so I will take a look tonight
and merge it in.

**Comment by veacks** [comment]
Cool, thanks.

**Pull request closed without merging**
